### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by jdmcs**
If a command line parameter is not specified, use the RESETOPL DOS environment variable as the source for the base address of the OPL2/3 chip. Useful for users of Ad Lib-compatible sound cards (including the Resound cards from TexElec), as they need only put "SET RESETOPL=0x388" in their autoexec.bat file and now they save having to type the base address each time they need to reset their OPL chip.

### CODE REVIEW

**Comment by stargo** [comment]
Hi,

thank you for your work! :-)

I would like to merge it, but your commit did not modify resetopl.c but added it again as RESETOPL.C, so both files are in the repository. Can you clean that up or should I try to fix it? (If I shoud try to fix it, I think you can give me permissions to modify your pull request in the lower right corner - "Allow edits from maintainers", see https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork )

**Comment by jdmcs** [comment]
Oops, rookie mistake. Then again I am a rookie with GitHub (they use SVN at work). I think I've fixed the duplicate files and you should now just see the one resetopl.c file.

**Comment by jdmcs** [comment]
But if there's still an issue, it looks like allow edits by maintainers is enabled.

**Comment by stargo** [comment]
Looks good, I'll squash the commits and merge to the master branch. Thanks :-)

**Pull request merged**
